wandb: Streaming LlamaIndex events to W&B at https://wandb.ai/arunk777/gemini-test/runs/onil2lxi
wandb: `WandbCallbackHandler` is currently in beta.
wandb: Please report any issues to https://github.com/wandb/wandb/issues with the tag `llamaindex`.
[nltk_data] Downloading package punkt to /Users/asanthan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/asanthan/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
Parsing nodes: 100%|██████████| 1/1 [00:00<00:00, 26.71it/s]

100%|██████████| 8/8 [00:03<00:00,  2.15it/s]
100%|██████████| 2/2 [00:01<00:00,  1.63it/s]
100%|██████████| 2/2 [00:01<00:00,  1.51it/s]
100%|██████████| 2/2 [00:01<00:00,  1.20it/s]
100%|██████████| 2/2 [00:01<00:00,  1.18it/s]

100%|██████████| 2/2 [00:03<00:00,  1.56s/it]
100%|██████████| 2/2 [00:01<00:00,  1.64it/s]
100%|██████████| 2/2 [00:01<00:00,  1.89it/s]
100%|██████████| 2/2 [00:01<00:00,  1.07it/s]
Batch processing of predictions:   0%|          | 0/5 [00:00<?, ?it/s]
                                               query  ...         query_by
0  What is the maximum number of axes that can be...  ...  ai (gemini-pro)
1  What are the safety features available in the ...  ...  ai (gemini-pro)
[2 rows x 5 columns]
Batch processing of predictions:   0%|          | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/utils/evaluation/rag_evaluation.py", line 156, in <module>
    loop = asyncio.run(batch())
  File "/Users/asanthan/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/asanthan/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/utils/evaluation/rag_evaluation.py", line 131, in batch
    gemini_pro_benchmark_df = await evaluator_benchmarker.arun(
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/utils/evaluation/pack/base.py", line 158, in arun
    await self._amake_predictions(batch_size, sleep_time_in_seconds)
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/utils/evaluation/pack/base.py", line 44, in _amake_predictions
    ] = await self.eval_dataset.amake_predictions_with(
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/venv/lib/python3.10/site-packages/llama_index/llama_dataset/base.py", line 294, in amake_predictions_with
    batch_predictions = await asyncio_mod.gather(
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/venv/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/venv/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/Users/asanthan/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/asanthan/.pyenv/versions/3.10.10/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/asanthan/.pyenv/versions/3.10.10/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/venv/lib/python3.10/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "/Users/asanthan/work/development/greenfield/demos/generative-ai/RAG/venv/lib/python3.10/site-packages/llama_index/llama_dataset/rag.py", line 129, in _apredict_example
    response = await predictor.aquery(example.query)
AttributeError: 'CorrectnessEvaluator' object has no attribute 'aquery'